### ISSUE TITLE
Piecewise Model Question

### ISSUE THREAD

**Issue by kylewschulz** [skorsu/Stats506_Project#18] opened 2020-11-24 23:43 UTC
Hi @ecikanek @skorsu , one more quick question - 

I noticed we've split slightly on the piecewise model, Erin has an intercept per step and Kevin has one intercept for the entire model. I think we just want one intercept (along with the 6 indicator variables and education and year), but just wanted to double check 

Kyle

**Comment by skorsu** [comment] 2020-11-24 23:46
According to the `ISLR`, we should include only one intercept term.

Kevin

**Comment by ecikanek** [comment] 2020-11-25 01:13
I will recheck my code. Hopefully it turns out to be the case that there is an easier solution than what I did initially! 

Erin

**Comment by ecikanek** [comment] 2020-11-25 01:52
I've corrected the piecewise model - the image is correct in the Stata_images file but I have not updated the Rmd yet. Attaching the image- let me know if this means we are all on the same page and we can close this ticket. 

<img width="644" alt="step_reg" src="https://user-images.githubusercontent.com/14208044/100172675-d517a200-2e96-11eb-9d18-a882e25a593d.png">

**Comment by skorsu** [comment] 2020-11-25 01:59
For the Piecewise Regression, I have one intercept term, which same as you. However, I have only five betas for age variable while you have six. Here is my model.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/71246225/100173155-f2993b80-2e97-11eb-87c5-c86828a4f163.png">

Kevin

**Comment by ecikanek** [comment] 2020-11-25 02:04
Hi Kevin, 

I can see the bins for your cuts starting between [28.3, 38.7] - does your model have a bin for those whose age is below 28? or [18, 28.3]? I'm attaching a screen grab of the variables that show the ranges that constitute their bins for my regression. 


<img width="359" alt="Screen Shot 2020-11-24 at 9 03 35 PM" src="https://user-images.githubusercontent.com/14208044/100173431-85d27100-2e98-11eb-9792-393f0a2c8ecf.png">

**Comment by ecikanek** [comment] 2020-11-25 02:07
@skorsu I also just looked at your Rcode: lm(wage ~ cut(age, 4) + edu + year, data = data) 

Since the cut(age,4) does that mean there are 4 cuts? Could that be the issue with the mismatch?

**Comment by skorsu** [comment] 2020-11-25 02:13
@ecikanek This is the cut(age,6) looks like in R.

<img width="581" alt="Screen Shot 2563-11-24 at 21 10 54" src="https://user-images.githubusercontent.com/71246225/100173988-96cfb200-2e99-11eb-8b83-c68166c5fab3.png">

It also has six levels like yours. However, when I use this into model, it treat the lowest group as a reference level.

**Comment by ecikanek** [comment] 2020-11-25 02:24
Ah! This may just be a difference in how the different programs create categories. Mine does not create a reference category and just has one for each bin. Perhaps if we just discuss this difference when we each talk about our code that would be useful - and possibly helpful for the tutorial.

**Comment by skorsu** [comment] 2020-11-25 02:26
Oh, that's the great idea!

**Comment by ecikanek** [comment] 2020-11-25 02:26
I am closing this issue :)

**Closed as completed by ecikanek** 2020-11-25 02:26 UTC
